import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { BaselimeRum } from '../../dist'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
const apiKey = process.env.NEXT_PUBLIC_BASELIME_KEY;

export default function RootLayout({
  children,
}: {
  children: any
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BaselimeRum apiKey={apiKey as string} enableWebVitals enableLocal>
          {children}
        </BaselimeRum>
      </body>
    </html>
  )
}
